### ISSUE TITLE
npm installation babel issue

### ISSUE THREAD

**Issue by jeremyabel** [Stinkstudios/sono#36]
trying to use the latest version of this module fails when doing npm install: 

```
> sono@2.1.2 postinstall /Users/jeremyabel/Documents/Workspace/webvr-mars/node_modules/sono
> babel src --out-dir ./

ReferenceError: Unknown plugin "external-helpers" specified in "/Users/jeremyabel/Documents/Workspace/webvr-mars/node_modules/sono/.babelrc" at 0, attempted to resolve relative to "/Users/jeremyabel/Documents/Workspace/webvr-mars/node_modules/sono"
    at /Users/jeremyabel/Documents/Workspace/webvr-mars/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/jeremyabel/Documents/Workspace/webvr-mars/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/jeremyabel/Documents/Workspace/webvr-mars/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/jeremyabel/Documents/Workspace/webvr-mars/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/jeremyabel/Documents/Workspace/webvr-mars/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/jeremyabel/Documents/Workspace/webvr-mars/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/jeremyabel/Documents/Workspace/webvr-mars/node_modules/babel-cli/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transform (/Users/jeremyabel/Documents/Workspace/webvr-mars/node_modules/babel-cli/lib/babel/util.js:50:22)
    at Object.compile (/Users/jeremyabel/Documents/Workspace/webvr-mars/node_modules/babel-cli/lib/babel/util.js:59:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sono@2.1.2 postinstall: `babel src --out-dir ./`
npm ERR! Exit status 1
```

**Comment by jeremyabel** [comment]
huh, it works fine if I uninstall it first then reinstall it. I had an old version installed previously. Disregard!

**Comment by ianmcgregor** [comment]
Thanks @jeremyabel it's good to know anyway. Btw 'webvr-mars' sounds intriguing ;)

**Comment by jeremyabel** [comment]
aw jeez I should have censored that out! shhhhhhhh
